Enrollments
ugandan-bois/Primer-Sprint pull request #30
Opened 2019-04-01 01:16 UTC by luis1415

enrollments

2019-04-01 01:19 UTC, juanfelito requested changes

2019-04-01 01:19 UTC, juanfelito commented on src/controllers/enrollments.js
> +    console.log(req.body)
No dejes los console.log

2019-04-01 01:25 UTC, luis1415 commented on src/controllers/enrollments.js
> +    console.log(req.body)
listo, ya los borre

2019-04-01 01:36 UTC, juanfelito submitted a review, later dismissed

2019-04-02 00:04 UTC, mateogo42 approved these changes

2019-04-02 00:04 UTC, merged